// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/u/home/bclary/eg1analysis/SKIMprotocol/analysiscode_v2.2/dilution_analysis/./DilutionVsCuts.cpp";

#endif
